import { Counter } from "@/components/Counter"
import type { NextPage } from "next"
import Head from "next/head"
import GitHub from "../components/icons/GitHub"
import styles from "./index.module.css"

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.wrapper}>
        <header className={styles.header}>
          <p>Logo</p>
          <p className={styles.links}>
            <span>Menu 1</span>
            <span>Menu 2</span>
            <span>Menu 3</span>
          </p>
        </header>

        <main className={styles.main}>
          <h1>Next TS ESLint starter</h1>
          <Counter />
          <div style={{ marginTop: 200 }}>
            <p>
              <strong>{"What's next?"}</strong>
            </p>
            <a href="https://gist.github.com/pom421/ea34eeb778b0d94fe85352dc27aada96">
              Needs some boilerplate for zod and React Hook Form&nbsp;?
            </a>
          </div>
        </main>

        <footer className={styles.footer}>
          <a href="https://github.com/pom421/next-ts-eslint-starter">
            <GitHub width={32} height={32} />
          </a>
        </footer>
      </div>
      {/* This global style on body makes CSS fills the entire height. */}
      {/* Référence: https://gist.github.com/dmurawsky/d45f068097d181c733a53687edce1919 */}
      <style global jsx>{`
        html,
        body,
        body > div:first-child,
        div#__next,
        div#__next > div {
          height: 100%;
        }
      `}</style>
    </>
  )
}

export default Home
